version: '3'

services:
  db:
    image: 'mariadb:10'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=framadate
  smtp:
    image: namshi/smtp
    environment:
      - MAILNAME=change.me
  app:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/entrypoint.sh:/entrypoint.sh
    environment:
      - SMTP_HOST=smtp
      - SMTP_PORT=25
      - SMTP_SECURE= # ø, 'ssl' or 'tls'
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
  adminer:
    image: dehy/adminer
    ports:
      - 8081:80
